In [8]:
# task 1 "Lists , Dictionaries and tupples"
nums = [3, 5, 7, 8, 12]

# Create an empty list to store cubes
cubes = []

# Compute the cube of each number in nums and append it to cubes
for num in nums:
    cubes.append(num ** 3)

print(cubes)

[27, 125, 343, 512, 1728]


In [10]:
# Tast 1.2
my_dict = {}

my_dict['parrot'] = 4
my_dict['spider'] = 8
my_dict['crab'] = 10

print(my_dict)

{'parrot': 4, 'spider': 8, 'crab': 10}


In [17]:
#  Task 1.3
my_dict = {
    'parrot': 2,
    'spider': 8,
    'crab': 10
}

# variable to sum the total number of legs
total_legs = 0

for animal, legs in my_dict.items():
    
    print(f"{animal} has {legs} legs.")
    
    total_legs += legs

print(f"Total number of legs: {total_legs}")

parrot has 2 legs.
spider has 8 legs.
crab has 10 legs.
Total number of legs: 20


In [19]:
# Task 1.4
A = (3, 9, 4, [5, 6])

A[3][0] = 8

print(A)

(3, 9, 4, [8, 6])


In [39]:
# Task 1.5

del A

print(A)

NameError: name 'A' is not defined

In [41]:
# Task 1.6
B = ('a', 'p', 'p', 'l', 'e')

count_p = B.count('p')

print(f"The number of occurrences of 'p' in the tuple is: {count_p}")

The number of occurrences of 'p' in the tuple is: 2


In [37]:
# Task 1.7

index_l = B.index('l')

print(f"The index of 'l' in the tuple is: {index_l}")

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [27]:
# Task 2 "Numpy"

#task 2.1

import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Matrix A as a NumPy array:")
print(A)

Matrix A as a NumPy array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
# Task 2.2
 
B = A[:2, 1:3]

print("Subarray B:")
print(B)

Subarray B:
[[2 3]
 [6 7]]


In [31]:
# Task 2.3
C = np.ones_like(A)

# Print the resulting matrix C
print("Matrix C (filled with ones):")
print(C)

Matrix C (filled with ones):
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [47]:
# Task 2.4
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
z = np.array([1, 0, 1])
C = np.zeros_like(A)
for col in range(A.shape[1]):
    C[:, col] = A[:, col] + z
print("Matrix C after adding vector z to each column of A:")
print(C)

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])

print("Matrix X:")
print(X)

print("Matrix Y:")
print(Y)

print("Vector v:")
print(v)

Matrix C after adding vector z to each column of A:
[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]
Matrix X:
[[1 2]
 [3 4]]
Matrix Y:
[[5 6]
 [7 8]]
Vector v:
[ 9 10]


In [51]:
# Task 2.5

result = X + Y

print("Matrix X:")
print(X)

print("Matrix Y:")
print(Y)

print("Sum of Matrix X and Matrix Y:")
print(result)

Matrix X:
[[1 2]
 [3 4]]
Matrix Y:
[[5 6]
 [7 8]]
Sum of Matrix X and Matrix Y:
[[ 6  8]
 [10 12]]


In [53]:
# Task 2.6

result = np.dot(X, Y) 

print("Matrix X:")
print(X)

print("Matrix Y:")
print(Y)

print("Product of Matrix X and Matrix Y:")
print(result)

Matrix X:
[[1 2]
 [3 4]]
Matrix Y:
[[5 6]
 [7 8]]
Product of Matrix X and Matrix Y:
[[19 22]
 [43 50]]


In [55]:
# Task 2.7

sqrt_Y = np.sqrt(Y)

print("Matrix Y:")
print(Y)

print("Element-wise square root of Matrix Y:")
print(sqrt_Y)

Matrix Y:
[[5 6]
 [7 8]]
Element-wise square root of Matrix Y:
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [57]:
# Task 2.8
import numpy as np

dot_product = np.dot(X, v) 

print("Matrix X:")
print(X)

print("Vector v:")
print(v)

print("Dot product of Matrix X and Vector v:")
print(dot_product)

Matrix X:
[[1 2]
 [3 4]]
Vector v:
[ 9 10]
Dot product of Matrix X and Vector v:
[29 67]


In [59]:
# Task 2.9
column_sums = np.sum(X, axis=0)

print("Matrix X:")
print(X)

print("Sum of each column of Matrix X:")
print(column_sums)

Matrix X:
[[1 2]
 [3 4]]
Sum of each column of Matrix X:
[4 6]


In [65]:
# Task 3 "Functions and loop"

# Task 3.1
def Compute(distance, time):
    
    if time == 0:
        raise ValueError("Time cannot be zero.")
    
    velocity = distance / time
    
    return velocity

distance = 100  
time = 20        

velocity = Compute(distance, time)

print("Velocity:", velocity, "meters per second")

Velocity: 5.0 meters per second


In [67]:
# Task 3.2

even_num = [2, 4, 6, 8, 10, 12]

def mult(numbers):
    product = 1
    
    for number in numbers:
        product *= number
    
    return product

product_of_evens = mult(even_num)

print("The product of all even numbers up to 12 is:", product_of_evens)

The product of all even numbers up to 12 is: 46080


In [69]:
# Task 4 "Pandas"

# Task 4.1
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print("First two rows of the DataFrame:")
print(df.head(2))


First two rows of the DataFrame:
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [71]:
# Task 4.2 

print("Second column of the DataFrame:")
print(df['C2'])

Second column of the DataFrame:
0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [73]:
# Task 4.3

df.rename(columns={'C3': 'B3'}, inplace=True)

print("DataFrame with updated column name:")
print(df)

DataFrame with updated column name:
   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [75]:
# Task 4.4

df['Sum'] = df.sum(axis=1)

print("DataFrame with the 'Sum' column:")
print(df)

DataFrame with the 'Sum' column:
   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [77]:
# Task 4.5

df['Sum'] = df.sum(axis=1)

# Print the DataFrame with the new 'Sum' column
print("DataFrame with the 'Sum' column:")
print(df)

DataFrame with the 'Sum' column:
   C1  C2  B3  C4  Sum
0   1   6   7   7   42
1   2   7   9   5   46
2   3   5   8   2   36
3   5   4   6   8   46
4   5   8   5   8   52


In [93]:
# Task 4.7
pd.set_option('display.max_rows', None)  
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)  

print("Complete DataFrame:")
print(df)

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.expand_frame_repr')


Complete DataFrame:
   C1  C2  B3  C4  Sum
0   1   6   7   7   42
1   2   7   9   5   46
2   3   5   8   2   36
3   5   4   6   8   46
4   5   8   5   8   52


In [91]:
# Task 4.8
print("Bottom 2 records of the DataFrame:")
print(df.tail(2))

Bottom 2 records of the DataFrame:
   C1  C2  B3  C4  Sum
3   5   4   6   8   46
4   5   8   5   8   52


In [95]:
# Task 4.9

print("DataFrame Information:")
print(df.info()) 

print("\nDescriptive Statistics:")
print(df.describe()) 
print("\nDataFrame Shape:")
print(df.shape)  

print("\nDataFrame Columns:")
print(df.columns)  

print("\nData Types of Columns:")
print(df.dtypes)  


DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
 2   B3      5 non-null      int64
 3   C4      5 non-null      int64
 4   Sum     5 non-null      int64
dtypes: int64(5)
memory usage: 332.0 bytes
None

Descriptive Statistics:
             C1        C2        B3       C4        Sum
count  5.000000  5.000000  5.000000  5.00000   5.000000
mean   3.200000  6.000000  7.000000  6.00000  44.400000
std    1.788854  1.581139  1.581139  2.54951   5.899152
min    1.000000  4.000000  5.000000  2.00000  36.000000
25%    2.000000  5.000000  6.000000  5.00000  42.000000
50%    3.000000  6.000000  7.000000  7.00000  46.000000
75%    5.000000  7.000000  8.000000  8.00000  46.000000
max    5.000000  8.000000  9.000000  8.00000  52.000000

DataFrame Shape:
(5, 5)

DataFrame Columns:
Index(['C1

In [97]:
# Task 4.10
import pandas as pd

rows, columns = df.shape

print(f"Shape of the DataFrame: {rows} x {columns}")

Shape of the DataFrame: 5 x 5


In [99]:
# Task 4.11

data = {
    'Name': ['Ali', 'Babar', 'Chaudhary', 'Dawood', 'Ehsan'],
    'Weight': [55, 72, 68, 75, 60]
}

df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Weight', ascending=True)

print("DataFrame sorted by 'Weight':")
print(sorted_df)

DataFrame sorted by 'Weight':
        Name  Weight
0        Ali      55
4      Ehsan      60
2  Chaudhary      68
1      Babar      72
3     Dawood      75


In [105]:
# Task 4.12

data = {
    'Name': ['Ahmed', 'Baber', 'hamad', np.nan, 'Ehsan'],
    'Weight': [55, 72, np.nan, 75, 60],
    'Height': [165, 180, 175, 170, np.nan]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("\nDataFrame with missing values indicated (isnull()):")
print(df.isnull())

df_dropped = df.dropna()

print("\nDataFrame after dropping rows with missing values (dropna()):")
print(df_dropped)

Original DataFrame:
    Name  Weight  Height
0  Ahmed    55.0   165.0
1  Baber    72.0   180.0
2  hamad     NaN   175.0
3    NaN    75.0   170.0
4  Ehsan    60.0     NaN

DataFrame with missing values indicated (isnull()):
    Name  Weight  Height
0  False   False   False
1  False   False   False
2  False    True   False
3   True   False   False
4  False   False    True

DataFrame after dropping rows with missing values (dropna()):
    Name  Weight  Height
0  Ahmed    55.0   165.0
1  Baber    72.0   180.0
